package com.kvdm.fuelled.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(
    entities = [
        FoodEntity::class,
        TodayGoalEntity::class,
        LogEntryEntity::class,
        SupplementEntity::class,
        SupplementTakenEntity::class,
        ProfileEntity::class,
        SlotTimeEntity::class,
        SlotDoneEntity::class,
        WaterTickEntity::class,
    ],
    // 8: supplement doses moved to their own per-logical-day table (SUPP-07), so the catalog
    // row lost its `taken` flag. Destructive migration, as everything here is (DatabaseBuilder):
    // every table is seeded or user-entered on device, and a stale `taken` column is precisely
    // what this version exists to drop.
    version = 8,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun foodDao(): FoodDao
    abstract fun todayDao(): TodayDao
    abstract fun supplementDao(): SupplementDao
    abstract fun profileDao(): ProfileDao
    abstract fun mealPlanDao(): MealPlanDao
}

// The actual implementation is generated by Room's KSP processor per platform.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
