package com.kvdm.fuelled.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(
    entities = [
        FoodEntity::class,
        TodayGoalEntity::class,
        LogEntryEntity::class,
        SupplementEntity::class,
        SupplementTakenEntity::class,
        ProfileEntity::class,
        SlotTimeEntity::class,
        SlotDoneEntity::class,
        WaterTickEntity::class,
        AppStateEntity::class,
        WeightEntity::class,
    ],
    // 8: supplement doses moved to their own per-logical-day table (SUPP-07), so the catalog
    // row lost its `taken` flag. Destructive migration, as everything here is (DatabaseBuilder):
    // every table is seeded or user-entered on device, and a stale `taken` column is precisely
    // what this version exists to drop.
    // 9: profile lost its duplicate goal columns (PERS-01 — one goal store; usability-pass F5).
    // 10: log rows store PER-SERVING macros + a `servings` multiple and their source `foodId`
    // (ENTRY-01 in-place serving edits, CAT-03 recents); foods gained `favourite`/`custom`
    // (CAT-01/CAT-02); `app_state` arrived for onboarding and the first-open instant (START-*).
    // 11: `weight_log` arrived — the outcome variable, one row per logical day (HIST-06);
    // `app_state` gained the unit system and the prep lead (SET-02/SET-07, settings decision
    // D8); supplement `timing` became the closed SupplementTiming set (SET-06), so seeded
    // rows are re-written with enum names rather than display labels.
    // 12: `today_goal` is a HISTORY — its primary key is the logical date the goal takes
    // effect from (GOAL-01/GOAL-02), so a target lowered today no longer re-scores the weeks
    // before it. The seeded default is effective from the beginning of time (GOAL-03).
    version = 12,
    exportSchema = true,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun foodDao(): FoodDao
    abstract fun todayDao(): TodayDao
    abstract fun supplementDao(): SupplementDao
    abstract fun profileDao(): ProfileDao
    abstract fun mealPlanDao(): MealPlanDao
    abstract fun appStateDao(): AppStateDao
    abstract fun weightDao(): WeightDao
}

// The actual implementation is generated by Room's KSP processor per platform.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
