# Native pods the app links. None by default: the ComposeApp KMP framework needs no pod.
# `create-cmp add firebase` adds the Firebase iOS SDKs inside the target block below.
platform :ios, '16.0'

# Static linkage pairs with the static ComposeApp.framework (isStatic = true).
use_frameworks! :linkage => :static

target 'iosApp' do
  # The native Firebase iOS SDKs the GitLive bindings link against: GitLive 2.1.0 is built against Firebase iOS 11.1.0 (create-cmp's version registry).
  pod 'FirebaseCore',          '~> 11.1'
  pod 'FirebaseAuth',          '~> 11.1'
  pod 'FirebaseFirestore',     '~> 11.1'
  pod 'FirebaseFunctions',     '~> 11.1'
  pod 'FirebaseStorage',       '~> 11.1'
  pod 'FirebaseMessaging',     '~> 11.1'
  pod 'FirebaseRemoteConfig',  '~> 11.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
