#!/usr/bin/env bash
#
# Generate the release signing key for Fuelled — locally, once, and never committed.
#
# Produces two files, BOTH gitignored:
#   keystore/fuelled-release.jks   the keystore itself
#   keystore.properties            the passwords and alias Gradle reads
#
# Passwords are generated here rather than chosen, so a weak one is not an option and the
# value never has to be typed, pasted or remembered anywhere in between.
#
# ── BACK THIS UP ────────────────────────────────────────────────────────────────────────
# Android identifies an app by its SIGNING KEY. Lose these two files and you cannot ship an
# update to anyone who installed a build signed with them — not a re-issue, not a recovery,
# not with support's help. The only fix is a new applicationId and every user reinstalling
# from scratch. Copy both files somewhere durable (a password manager's file attachment, an
# encrypted backup) the moment this script finishes.
#
# Re-running is REFUSED while the files exist: a second run would mint a different key under
# the same name, and every build after it would be an app the installed one cannot update.

set -euo pipefail

cd "$(dirname "$0")/.."

KEYSTORE_DIR="keystore"
KEYSTORE_FILE="$KEYSTORE_DIR/fuelled-release.jks"
PROPS_FILE="keystore.properties"
ALIAS="fuelled"
# 10000 days ~ 27 years. Play requires a key valid past 2033; comfortably clear.
VALIDITY_DAYS=10000

if [[ -f "$KEYSTORE_FILE" || -f "$PROPS_FILE" ]]; then
  echo "Refusing to overwrite an existing signing key."
  echo "  $KEYSTORE_FILE $([[ -f "$KEYSTORE_FILE" ]] && echo '(exists)' || echo '(missing)')"
  echo "  $PROPS_FILE $([[ -f "$PROPS_FILE" ]] && echo '(exists)' || echo '(missing)')"
  echo
  echo "A second key under the same name cannot update apps signed with the first."
  echo "If you genuinely mean to start over, move both files aside by hand first."
  exit 1
fi

command -v keytool >/dev/null 2>&1 || {
  echo "keytool not found — it ships with the JDK. Install a JDK or put its bin/ on PATH."
  exit 1
}

command -v openssl >/dev/null 2>&1 || {
  echo "openssl not found — needed to generate the passwords."
  exit 1
}

# 32 alphanumeric characters from the OS CSPRNG. Never echoed to the terminal.
#
# Every stage consumes a FINITE input to completion: `openssl rand` writes a fixed number of
# bytes and exits, so nothing downstream closes a pipe early. Draining /dev/urandom through
# `head -c` instead makes `head` close the pipe on `tr`, which is a SIGPIPE, which under
# `set -o pipefail` fails the script with exit 141 having written nothing (observed, 2026-08-01).
gen_password() { openssl rand -base64 96 | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-32; }

# ONE password, used for both the store and the key.
#
# Not laziness: keytool's default format is PKCS12, which does not support a key password
# distinct from the store password — given two it prints a warning and silently IGNORES the
# key password. Generating two would produce a keystore.properties whose keyPassword is a
# value nothing accepts, and the failure would surface later, during a release build, looking
# like a corrupt keystore. One password is the format's actual behaviour, stated.
STORE_PASSWORD="$(gen_password)"
KEY_PASSWORD="$STORE_PASSWORD"

mkdir -p "$KEYSTORE_DIR"

keytool -genkeypair \
  -v \
  -keystore "$KEYSTORE_FILE" \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 4096 \
  -validity "$VALIDITY_DAYS" \
  -storepass "$STORE_PASSWORD" \
  -keypass "$KEY_PASSWORD" \
  -storetype PKCS12 \
  -dname "CN=Fuelled, OU=Fuelled, O=Fuelled, L=Unknown, ST=Unknown, C=ZA" \
  >/dev/null 2>&1

cat > "$PROPS_FILE" <<EOF
# Release signing for Fuelled — LOCAL ONLY, never committed (see .gitignore).
# Generated by scripts/generate-signing-key.sh. Back this file up together with
# $KEYSTORE_FILE — losing either one ends your ability to update installed builds.
storeFile=$KEYSTORE_FILE
storePassword=$STORE_PASSWORD
keyAlias=$ALIAS
keyPassword=$KEY_PASSWORD
EOF

chmod 600 "$PROPS_FILE"
chmod 600 "$KEYSTORE_FILE"

echo "✓ Signing key generated."
echo "    $KEYSTORE_FILE   (RSA 4096, valid ${VALIDITY_DAYS} days, alias '$ALIAS')"
echo "    $PROPS_FILE      (mode 600)"
echo
echo "Both are gitignored. ./gradlew :composeApp:assembleRelease now produces a SIGNED apk."
echo "Without them the release build still succeeds, unsigned — CI does not need secrets to"
echo "compile, only to publish."
echo
echo "BACK UP BOTH FILES NOW. There is no recovery path for a lost Android signing key."
